config/routes.rb
Rails.application.routes.draw do
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  resources :sessions, only: [:index, :show, :destroy]
  resource :email, only: [:edit, :update]
  resource :email_verification, only: [:edit, :create]
  resource :password, only: [:edit, :update]
  resource :password_reset, only: [:new, :edit, :create, :update]
  resource :registration, only: :destroy
  resource :sudo, only: [:new, :create]
  root 'home#index'

  resources :todos do
    patch :change_status, on: :member
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_action :authenticate

  before_action :set_user, only: %i[ edit update ]

  def new; end

  def edit; end

  def create
    if @user = User.find_by(email: params[:email], verified: true)
      IdentityMailer.with(user: @user).password_reset_provision.deliver_later
      redirect_to sign_in_path, notice: "Check your email for reset instructions"
    else
      redirect_to new_password_reset_path, alert: "You can't reset your password until you verify your email"
    end
  end

  def update
    if @user.update(user_params)
      redirect_to sign_in_path, notice: "Your password was reset successfully. Please sign in"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def set_user
      @user = User.find_signed!(params[:token], purpose: :password_reset)
    rescue
      redirect_to new_password_reset_path, alert: "That password reset link is invalid"
    end

    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end
end

app/views/password_resets/edit.html.erb
<%= button_to "Back", root_path, method: :get,
                      class: 'w-full inline-flex justify-center py-2 px-4 border border-gray-300 rounded-md shadow-sm bg-white text-sm font-medium text-gray-500 hover:bg-gray-50 mt-4 dark:bg-gray-800 dark:text-gray-500 dark:border-gray-500 dark:hover:border-gray-400 dark:hover:text-gray-300 dark:hover:bg-gray-700' %>

<h1>Reset your password</h1>

<%= form_with(model: @user, url: password_reset_path) do |form| %>
  <% if @user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field_tag :token, params[:token] %>

  <div>
    <%= form.label :password, "New password", style: "display: block" %>
    <%= form.password_field :password, autofocus: true, autocomplete: "new-password" %>
    <div>12 characters minimum.</div>
  </div>

  <div>
    <%= form.label :password_confirmation, "Confirm new password", style: "display: block" %>
    <%= form.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div>
    <%= form.submit "Save changes" %>
  </div>
<% end %>

app/views/password_resets/new.html.erb
<%= button_to "Back", root_path, method: :get,
                      class: 'w-full inline-flex justify-center py-2 px-4 border border-gray-300 rounded-md shadow-sm bg-white text-sm font-medium text-gray-500 hover:bg-gray-50 mt-4 dark:bg-gray-800 dark:text-gray-500 dark:border-gray-500 dark:hover:border-gray-400 dark:hover:text-gray-300 dark:hover:bg-gray-700' %>

<h1>Forgot your password?</h1>

<%= form_with(url: password_reset_path) do |form| %>
  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.email_field :email, autofocus: true, required: true %>
  </div>

  <div>
    <%= form.submit "Send password reset email" %>
  </div>
<% end %>