config/routes.rb
Rails.application.routes.draw do
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  resources :sessions, only: [:index, :show, :destroy]
  resource :email, only: [:edit, :update]
  resource :email_verification, only: [:edit, :create]
  resource :password, only: [:edit, :update]
  resource :password_reset, only: [:new, :edit, :create, :update]
  resource :registration, only: :destroy
  resource :sudo, only: [:new, :create]
  root 'home#index'

  resources :todos do
    patch :change_status, on: :member
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<section class="bg-white dark:bg-gray-800">
  <nav class="container p-6 mx-auto lg:flex lg:justify-between lg:items-center">
    <div class="flex items-center justify-between">
      <div>
        <%= link_to 'TODO', root_path, class: 'text-2xl font-bold text-gray-800 dark:text-white lg:text-3xl hover:text-gray-700 dark:hover:text-gray-300' %>
      </div>

      <!-- Mobile menu button -->
      <div class="flex lg:hidden">
        <button type="button" class="text-gray-500 hover:text-gray-600 focus:outline-none focus:text-gray-600" aria-label="toggle menu">
          <svg viewbox="0 0 24 24" class="w-6 h-6 fill-current">
            <path fill-rule="evenodd" d="M4 5h16a1 1 0 0 1 0 2H4a1 1 0 1 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2z"></path>
          </svg>
        </button>
      </div>
    </div>

    <!-- Mobile Menu open: "block", Menu closed: "hidden" -->
    <div class="flex flex-col mt-4 space-y-2 mx-4 flex-1 lg:mx-8 lg:mt-0 lg:flex-row lg:space-y-0">
      <%= link_to "TODO List", todos_path, class: 'font-bold text-gray-700 dark:text-gray-200 lg:px-6 dark:hover:text-blue-400 hover:text-blue-500' %>
    </div>
    <div class="flex items-center">
      <div data-controller="dropdown" class="relative inline-block text-left mr-1">
        <div>
          <span class="rounded-md shadow-sm">
            <%= link_to Current.user&.email, 'javascript:void(0);', class: 'block h-10 px-5 py-2 mt-4 text-sm text-center text-gray-700 capitalize transition-colors duration-200 transform border rounded-md dark:text-gray-400 dark:border-gray-400 dark:hover:bg-gray-700 dark:hover:text-blue-400 lg:mt-0 hover:bg-gray-100 dark:hover:border-blue-400 lg:w-auto transition ease-in-out duration-400',
                                              data: { dropdown_target: "button", action: "click->dropdown#toggleMenu click@window->dropdown#hideMenu keyup@window->dropdown#closeWithKeyboard" } %>
          </span>
        </div>

        <!-- add transition data attributes. -->
        <div
          class="z-10 origin-top-right absolute left-0 mt-3 w-60 rounded-md shadow-lg hidden"
          data-dropdown-target="menu"
          data-transition-enter="transition ease-out duration-100"
          data-transition-enter-start="transform opacity-0 scale-95"
          data-transition-enter-end="transform opacity-100 scale-100"
          data-transition-leave="transition ease-in duration-75"
          data-transition-leave-start="transform opacity-100 scale-100"
          data-transition-leave-end="transform opacity-0 scale-95">
          <div class="rounded-md bg-gray-800 border border-gray-600 shadow-xs">
            <div class="" role="menu" aria-orientation="vertical" aria-labelledby="options-menu">
              <div class="bg-gray-800 shadow rounded border border-gray-600 overflow-hidden">
                <div class="flex flex-col">
                  <%= link_to "Change password", edit_password_path, class: 'mt-1 mx-1 rounded text-gray-700 dark:text-gray-200 dark:hover:bg-gray-700 lg:px-6 lg:py-2 dark:hover:text-blue-400 hover:text-blue-500 appearance-none', data: { action:
                  "click->dropdown#clickItem" } %>
                  <%= link_to "Change email", edit_email_path, class: 'mx-1 rounded text-gray-700 dark:text-gray-200 dark:hover:bg-gray-700 lg:px-6 lg:py-2 dark:hover:text-blue-400 hover:text-blue-500 appearance-none', data: { action: "click->dropdown#clickItem" } %>
                  <%= link_to "Sessions", sessions_path, class: 'mx-1 rounded text-gray-700 dark:text-gray-200 dark:hover:bg-gray-700 lg:px-6 lg:py-2 dark:hover:text-blue-400 hover:text-blue-500 appearance-none', data: { action: "click->dropdown#clickItem" } %>
                  <%= button_to "Cancel my account", registration_path, method: :delete, form_class: "mx-1", class: 'flex w-full rounded text-gray-700 dark:text-gray-200 dark:hover:bg-gray-700 lg:px-6 lg:py-2 dark:hover:text-blue-400 hover:text-blue-500
                  appearance-none', data: { action: "click->dropdown#clickItem" } %>
                  <%= button_to "Log out", Current.session, method: :delete, form_class: "mx-1", class: 'flex w-full mb-1 rounded text-gray-700 dark:text-gray-200 dark:hover:bg-gray-700 lg:px-6 lg:py-2 dark:hover:text-blue-400 hover:text-blue-500 appearance-none',
                  data: { action: "click->dropdown#clickItem" } %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </nav>

  <div class="container flex flex-col px-6 py-10 mx-auto space-y-6 lg:h-[32rem] lg:py-16 lg:flex-row lg:items-center">
    <div class="w-full lg:w-1/2">
      <div class="lg:max-w-lg">
        <h1 class="text-3xl font-bold tracking-wide text-gray-800 dark:text-white lg:text-5xl">
          Easiest way to create your website
        </h1>

        <div class="mt-8 space-y-5">
          <p class="flex items-center -mx-2 text-gray-700 dark:text-gray-200">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 mx-2 text-blue-500" fill="none" viewbox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
            </svg>

            <span class="mx-2">Clean and Simple Layout</span>
          </p>
          <p class="flex items-center -mx-2 text-gray-700 dark:text-gray-200">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 mx-2 text-blue-500" fill="none" viewbox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
            </svg>

            <span class="mx-2">Just Copy Paste Codeing</span>
          </p>
          <p class="flex items-center -mx-2 text-gray-700 dark:text-gray-200">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 mx-2 text-blue-500" fill="none" viewbox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
            </svg>

            <span class="mx-2">Easy to Use</span>
          </p>
        </div>
      </div>
      <div class="w-full mt-8 bg-transparent border rounded-md lg:max-w-sm dark:border-gray-700 focus-within:border-blue-400 focus-within:ring focus-within:ring-blue-300 dark:focus-within:border-blue-400 focus-within:ring-opacity-40">
        <form class="flex flex-col lg:flex-row">
          <input
            type="email"
            placeholder="Enter your email address"
            class="flex-1 h-10 px-4 py-2 m-1 text-gray-700 placeholder-gray-400 bg-transparent border-none appearance-none dark:text-gray-200 focus:outline-none focus:placeholder-transparent focus:ring-0"/>

          <button type="button" class="h-10 px-4 py-2 m-1 text-white transition-colors duration-200 transform bg-blue-500 rounded-md hover:bg-blue-400 focus:outline-none focus:bg-blue-400">
            Join Us
          </button>
        </form>
      </div>
    </div>
    <div class="flex items-center justify-center w-full h-96 lg:w-1/2">
      <img
        class="object-cover w-full h-full mx-auto rounded-md lg:max-w-2xl"
        src="https://images.unsplash.com/photo-1543269664-7eef42226a21?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80"
        alt="glasses photo">
    </div>
  </div>
</section>

<section>  
  <%= render "shared/footer" %>
</section>