config/routes.rb
Rails.application.routes.draw do
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  resources :sessions, only: [:index, :show, :destroy]
  resource :email, only: [:edit, :update]
  resource :email_verification, only: [:edit, :create]
  resource :password, only: [:edit, :update]
  resource :password_reset, only: [:new, :edit, :create, :update]
  resource :registration, only: :destroy
  resource :sudo, only: [:new, :create]
  root 'home#index'

  resources :todos do
    patch :change_status, on: :member
  end
end

app/models/todo.rb
class Todo < ApplicationRecord
  enum status: %i[incomplete complete]

  validates_presence_of :name
  validates :status, inclusion: { in: statuses.stringify_keys.keys }
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate
  before_action :set_todo, only: %i[ show edit update destroy change_status ]

  def index
    @status = params[:status].presence || 'incomplete'
    @todos = Todo.where(status: @status )
  end

  def show; end

  def new
    @todo = Todo.new
  end

  def edit
  end

  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        flash.now[:notice] = "Todo was successfully created."
        format.turbo_stream
        format.html { redirect_to root_url, notice: "Todo was successfully created." }
      else
        flash.now[:alert] = @todo.errors.full_messages.join('; ')
        format.turbo_stream
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @todo.update(todo_params)
        flash.now[:notice] = "Todo was successfully updated."
        format.turbo_stream
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully updated." }
      else
        flash.now[:alert] = @todo.errors.full_messages.join('; ')
        format.turbo_stream
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @todo.destroy

    respond_to do |format|
      flash.now[:notice] = "Todo was successfully destroyed."
      format.turbo_stream { render turbo_stream: turbo_stream.remove("#{helpers.dom_id(@todo)}_container") }
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
    end
  end

  def change_status
    @todo.update(status: todo_params[:status])

    respond_to do |format|
      flash.now[:notice] = "Updated todo status."
      format.turbo_stream { render turbo_stream: turbo_stream.remove("#{helpers.dom_id(@todo)}_container") }
      format.html { redirect_to todos_path, notice: "Updated todo status." }
    end
  end

  private

    def set_todo
      @todo = Todo.find(params[:id])
    end

    def todo_params
      params.require(:todo).permit(:name, :status)
    end
end

app/views/todos/_form.html.erb
<%= form_with(model: todo, id: "#{dom_id(todo)}_form") do |form| %>
  <%= render 'shared/errors', object: form.object %>
  <div class="flex items-stretch flex-grow" style='padding-right: 12px;'>
    <%= form.label :name, class: "sr-only" %>
    <%= form.text_field :name, class: "block w-full rounded-none rounded-l-md sm:text-sm border-gray-300 dark:bg-gray-200 dark:focus:bg-gray-100 dark:text-gray-700 font-bold", placeholder: "Add a new todo..." %>
    <%= form.submit class: "-ml-px relative px-4 py-2 border border-blue-600 text-sm font-medium rounded-r-md text-white bg-blue-600 hover:bg-blue-700" %>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<li id="<%= "#{dom_id(todo)}_container" %>" class="py-2 px-4 border-b border-gray-300">
  <%= turbo_frame_tag dom_id(todo) do %>
    <div class="flex justify-between items-center space-x-3">
      <%= link_to todo.name, edit_todo_path(todo), class: todo.complete? ? 'line-through' : '' %>

      <div class="flex justify-end space-x-3">
        <% if todo.complete? %>
          <%= button_to change_status_todo_path(todo, todo: { status: 'incomplete' }), class: "bg-green-600 px-4 py-2 rounded hover:bg-green-700", method: :patch do %>
            <span class="sr-only">Mark as incomplete</span>
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-white" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
            </svg>
          <% end %>
        <% else %>
          <%= button_to change_status_todo_path(todo, todo: { status: 'complete' }), class: "bg-gray-400 px-4 py-2 rounded hover:bg-green-700", method: :patch do %>
            <span class="sr-only">Mark as complete</span>
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-white" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
            </svg>
          <% end %>
        <% end %>

        <%= button_to todo_path(todo), class: "bg-red-600 px-4 py-2 rounded hover:bg-red-700", method: :delete do %>
          <span class="sr-only">Delete</span>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-white" viewBox="0 0 20 20" fill="currentColor" title="Delete todo">
            <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
          </svg>
        <% end %>
      </div>
    </div>
  <% end %>
</li>

app/views/todos/create.turbo_stream.erb
<% if @todo.errors.any? %>
  <%= turbo_stream.replace("#{dom_id(@todo)}_form", partial: "form", locals: { todo: @todo }) %>
<% else %>
  <%= turbo_stream.append "todos" do %>
    <%= render "todo", todo: @todo %>
  <% end %>
  <%= turbo_stream.replace "#{dom_id(Todo.new)}_form" do %>
    <%= render "form", todo: Todo.new %>
  <% end %>
<% end %>

<%= turbo_stream.prepend "flash", partial: "shared/flash" %>

app/views/todos/edit.html.erb
<%= turbo_frame_tag dom_id(@todo) do %>
  <%= render "form", todo: @todo %>
<% end %>

app/views/todos/index.html.erb
<%= button_to "Back", root_path, method: :get,
                      class: 'inline-flex justify-center py-2 px-4 border border-gray-300 rounded-md shadow-sm bg-white text-sm font-medium text-gray-500 hover:bg-gray-50 mt-4 dark:bg-gray-800 dark:text-gray-500 dark:border-gray-500 dark:hover:border-gray-400 dark:hover:text-gray-300 dark:hover:bg-gray-700' %>

<div class="mx-auto w-2/3 mt-28">
  <h2 class="text-3xl text-gray-900 dark:text-gray-300 font-bold mb-2">
    Your todos
  </h2>
  <%= turbo_frame_tag "todos-container", class: "block max-w-2xl w-full bg-white dark:bg-gray-600 py-8 px-4 border border-gray-600 rounded shadow-sm" do %>
  <div class="w-full mb-4">
    <ul class="flex space-x-2 justify-center">
      <li>
        <%= link_to "Incomplete", todos_path(status: "incomplete"), class: "inline-block py-4 px-4 text-sm font-medium text-center text-gray-500 dark:text-gray-400 border-b-2 #{@status == 'incomplete' ? 'border-gray-400 dark:hover:border-gray-300' :
        'border-transparent'} hover:text-gray-600 dark:hover:hover:text-gray-300" %>
      <li>
        <%= link_to "Complete", todos_path(status: "complete"), class: "inline-block py-4 px-4 text-sm font-medium text-center text-gray-500 dark:text-gray-400 border-b-2 #{@status == 'complete' ? 'border-gray-400 dark:hover:border-gray-300' :
        'border-transparent'} hover:text-gray-600 dark:hover:hover:text-gray-300" %>
      </li>
    </ul>
  </div>
  <% unless params[:status] == "complete" %>
    <div class="px-4">
      <%= render "form", todo: Todo.new %>
    </div>
  <% end %>
  <ul id="todos" class='px-3 mt-3'>
    <%= render @todos %>
  </ul>
<% end %>
</div>

app/views/todos/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New todo</h1>

  <%= render "form", todo: @todo %>

  <%= link_to 'Back to todos', todos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/todos/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @todo %>

    <%= link_to 'Edit this todo', edit_todo_path(@todo), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this todo', todo_path(@todo), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to todos', todos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/todos/update.turbo_stream.erb
<% if @todo.errors.any? %>
  <%= turbo_stream.replace("#{dom_id(@todo)}_form", partial: "form", locals: { todo: @todo }) %>
<% else %>
  <%= turbo_stream.replace "#{dom_id(@todo)}_container" do %>
    <%= render "todo", todo: @todo %>
  <% end %>
<% end %>

<%= turbo_stream.prepend "flash", partial: "shared/flash" %>