config/routes.rb
Rails.application.routes.draw do
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  resources :sessions, only: [:index, :show, :destroy]
  resource :email, only: [:edit, :update]
  resource :email_verification, only: [:edit, :create]
  resource :password, only: [:edit, :update]
  resource :password_reset, only: [:new, :edit, :create, :update]
  resource :registration, only: :destroy
  resource :sudo, only: [:new, :create]
  root 'home#index'

  resources :todos do
    patch :change_status, on: :member
  end
end

app/controllers/sudos_controller.rb
class SudosController < ApplicationController
  def new
  end

  def create
    session = Current.session

    if session.user.authenticate(params[:password])
      session.update!(sudo_at: Time.current); redirect_to(params[:proceed_to_url])
    else
      redirect_to new_sudo_path(proceed_to_url: params[:proceed_to_url]), alert: "The password you entered is incorrect"
    end
  end
end

app/views/sudos/new.html.erb
<%= button_to "Back", root_path, method: :get,
                      class: 'inline-flex justify-center py-2 px-4 border border-gray-300 rounded-md shadow-sm bg-white text-sm font-medium text-gray-500 hover:bg-gray-50 mt-4 dark:bg-gray-800 dark:text-gray-500 dark:border-gray-500 dark:hover:border-gray-400 dark:hover:text-gray-300 dark:hover:bg-gray-700' %>

<div class="min-h-full flex flex-col justify-center py-12 sm:px-6 lg:px-8 w-full">
  <div class="sm:mx-auto sm:w-full sm:max-w-md">
    <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900 dark:text-gray-400">Enter your password to continue</h2>
  </div>

  <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
    <div class="bg-white dark:bg-gray-600 py-8 px-4 shadow sm:rounded-lg sm:px-10">
      <%= form_with(url: sudo_path, class: 'space-y-6' ) do |form| %>

        <%= hidden_field_tag :proceed_to_url, params[:proceed_to_url] %>
        <div>
          <%= form.label :password, class: 'block text-sm font-medium text-gray-700 dark:text-gray-300'%>
          <div class="mt-1">
            <%= form.password_field :password, autofocus: true, autocomplete: "current-password",
                          class: "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
          </div>
        </div>

        <div>
          <%= form.submit "Continue", class: "w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
        </div>
      <% end %>
      <div class="mt-6">
        <div class="relative">
          <div class="absolute inset-0 flex items-center">
            <div class="w-full border-t border-gray-300"></div>
          </div>
          <div class="relative flex justify-center text-sm">
            <span class="px-2 bg-white text-gray-500 dark:bg-gray-400 dark:text-gray-700">Forgot your password?</span>
          </div>
        </div>
      </div>
      <div class='mt-6 text-center'>
        We'll help you
        <%= link_to "reset it", new_password_reset_path,
                      class: 'justify-center px-2 font-medium dark:hover:text-gray-500'%>
        so you can continue.
      </div>
    </div>
  </div>
</div>